### ISSUE TITLE
Upload Artifacts directly to Github Pages

### ISSUE THREAD

**Issue by Garados007** [AllenInstitute/MIES#1777]
Github supports uploading artifacts directly to Github Pages: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

Using this needs some configuration in the project settings and a job like this one:

```yaml
DeployGithubPages:
    name: Deploy Github Pages
    needs:
      - RunPR
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        continue-on-error: false
        with:
          name: coverage-report
          path: report
      - name: Upload artifacts for Github Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: report
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

This is a beta feature at the moment.
